### ISSUE TITLE
Missing documentation and bad links

### ISSUE THREAD

**Issue by tonyhallett** [stryker-mutator/stryker-handbook#18]
https://github.com/stryker-mutator/stryker-handbook No FAQ and no Technical Reference links.
Yet technical reference is here - https://github.com/stryker-mutator/stryker-handbook/tree/master/stryker/technical-reference

Javascript &Typescript Getting Started links to empty md file as does Mutation Testing.

**Comment by nicojs** [comment]
Thanks 😅 

Feel free to improve the handbook with small PR's. We'd be happy to review them quickly.
