### ISSUE TITLE
Striker run in parallel?

### ISSUE THREAD

**Issue by LucasBadico** [stryker-mutator/stryker-handbook#24]
I'm look into mutators test frameworks. And found striker a good option, but in any place it talks aboult the paraller runners. There is anything that I'm missing?

**Comment by nicojs** [comment]
Yeah, you can add a section about it if you want! Stryker.NET, Stryker4s and Stryker all use test runner processes in parallel to speed up the mutation testing process.

**Comment by LucasBadico** [comment]
I will add this. It's a important point.

**Comment by hugo-vrijswijk** [comment]
Documentation about technical implementations is still welcome! But can now be done in each Stryker specific repo in its `docs/` folder
