### ISSUE TITLE
Rename PluginKind to PluginType

### ISSUE THREAD

**Issue by dance-cmdr** [stryker-mutator/stryker-handbook#25]
Hi there. 

First, I want to thank you for the amazing work you've done. 

I'm making a stryker-json-reporter in order to dump the report in a json file and then consume it from another app for historical purposes.

Reading about plugins I came across the term PluginKind. This is probably a neat but, would you be alright if I rename all of it's singular and plural occurrences to PluginType instead? 

https://github.com/stryker-mutator/stryker-handbook/blob/master/stryker/api/plugins.md

Cheers

**Comment by nicojs** [comment]
Hi @dance-cmdr. Your help would be much appreciated, but we like `PluginKind` more than `PluginType`. In general, everything in TypeScript is a type, so I try to avoid the `type` postfix whenever possible.

It would be awesome if the json reporter could be generic for more people to use. If you want, you can add it to our standard reporters: https://github.com/stryker-mutator/stryker/tree/master/packages/core/src/reporters

If you're interested in adding this, we would be grateful 💗! The JSON format should be in sync with [mutation-testing-report-schema](https://github.com/stryker-mutator/mutation-testing-elements/tree/master/packages/mutation-testing-report-schema), which is exactly what is delivered in the `onMutationTestReportReady` event. So it should be straightforward to add.

**Comment by dance-cmdr** [comment]
Fair enough about the kind! 

Yes, the json reporter will simply drop a json file in ./reports and then you do whatever you want with it. We will just copy it somewhere else and consume it from there, s,o that is not the concern of stryker or the reporter.

Thanks for the tips btw.

**Comment by dance-cmdr** [comment]
I'm going to close the issue as it is not relevant anymore.

**Comment by nicojs** [comment]
Thanks! Let's discus in #1814 :+1:
