### ISSUE TITLE
Failed to build the mutated assembly due to unrecoverable error: error CS0518: Predefined type 'System.Attribute' is not defined or imported

### ISSUE THREAD

**Issue by NanoRossi** [stryker-mutator/stryker-handbook#31]
The title error appears when attempting to build. I have numerous test projects which have worked without issue now I am suddenly seeing this error. Any help would be appreciated

**Comment by simondel** [comment]
Hi @NanoRossi, is your issue related to this documentation repository or did you mean to place your issue here: https://github.com/stryker-mutator/stryker-net ?

**Comment by NanoRossi** [comment]
Apologies yes I did mean to post there!

**Comment by simondel** [comment]
No problem :) I hope you get a solution to your issue 👍
