### ISSUE TITLE
The fate of stryker-handbook

### ISSUE THREAD

**Issue by bartekleon** [stryker-mutator/stryker-handbook#42]
I can see, that this repository is not updated very often, and it mostly duplicates things we already have in documentation. Should we still care and maintain this project? Or we could find more important parts not included in docs and send there?

**Comment by hugo-vrijswijk** [comment]
Anything that we did need from here was moved to either the website, mutation-testing-elements or stryker-specific repos and is now all available on the website. So yeah this repo should not be maintained anymore. We just need to update any files to now link to the website instead

**Comment by hugo-vrijswijk** [comment]
Done!
